apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: ''
  REDIS_HOST: "redis-master.default.svc.cluster.local"
  REDIS_PORT: "6379"
  PAYLOAD: "180000"   # ~180KB
  CONCURRENCY: "20"
  REQUESTS: "50000"