name: 'Dynamic Registry Login'
description: 'Auto login to AWS ECR, GCP GAR, or GHCR based on Image URL'
author: 'kangservice.cloud'

inputs:
  image_ref:
    required: true
    description: 'Full image repository URL'

  # AWS Credential
  aws_region:
    required: false
  aws_role_to_assume:
    required: false
  aws_access_key_id:
    required: false
  aws_secret_access_key:
    required: false

# GCP Credential (Shared Project)
  gcp_project_shared:
    required: false
    description: 'GCP Project ID for Shared/DevOps Registry Hub'
  gcp_sa_shared:
    required: false
    description: 'Shared Service Account JSON with cross-project access'

  # GCP Credential (Multi-Project)
  gcp_project_dev:
    required: false
  gcp_sa_dev:
    required: false
  gcp_project_stg:
    required: false
  gcp_sa_stg:
    required: false
  gcp_project_prd:
    required: false
  gcp_sa_prd:
    required: false

  
  # GHCR Credential
  ghcr_domain:
    required: false
    default: "ghcr.io"

  # Docker Hub Credential
  dockerhub_username:
    required: false
  dockerhub_token:
    required: false


runs:
  using: "composite"
  steps:
    # AUTO-LOGIN AWS ECR
    - name: Configure AWS credentials
      if: contains(inputs.image_ref, 'amazonaws.com')
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        
    - name: Login to Amazon ECR
      if: contains(inputs.image_ref, 'amazonaws.com')
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    # GCP LOGIN
    - name: Determine GCP Service Account
      if: contains(inputs.image_ref, 'docker.pkg.dev')
      shell: bash
      env:
        IMAGE_REF: ${{ inputs.image_ref }}
        GCP_PROJECT_SHARED: ${{ inputs.gcp_project_shared }}
        GCP_SA_SHARED: ${{ inputs.gcp_sa_shared }}
        GCP_PROJECT_DEV: ${{ inputs.gcp_project_dev }}
        GCP_SA_DEV: ${{ inputs.gcp_sa_dev }}
        GCP_PROJECT_STG: ${{ inputs.gcp_project_stg }}
        GCP_SA_STG: ${{ inputs.gcp_sa_stg }}
        GCP_PROJECT_PRD: ${{ inputs.gcp_project_prd }}
        GCP_SA_PRD: ${{ inputs.gcp_sa_PRD }} # Pastikan casing sesuai nama input Anda (PRD/prd)
      run: |
        if [[ -n "$GCP_PROJECT_SHARED" && "$IMAGE_REF" == *"$GCP_PROJECT_SHARED"* ]]; then
          echo "SA_JSON<<EOF" >> $GITHUB_ENV
          echo "$GCP_SA_SHARED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        elif [[ -n "$GCP_PROJECT_DEV" && "$IMAGE_REF" == *"$GCP_PROJECT_DEV"* ]]; then
          echo "SA_JSON<<EOF" >> $GITHUB_ENV
          echo "$GCP_SA_DEV" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        elif [[ -n "$GCP_PROJECT_STG" && "$IMAGE_REF" == *"$GCP_PROJECT_STG"* ]]; then
          echo "SA_JSON<<EOF" >> $GITHUB_ENV
          echo "$GCP_SA_STG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        elif [[ -n "$GCP_PROJECT_PRD" && "$IMAGE_REF" == *"$GCP_PROJECT_PRD"* ]]; then
          echo "SA_JSON<<EOF" >> $GITHUB_ENV
          echo "$GCP_SA_PRD" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          echo "❌ Error: String image_ref not matched with any GCP projects"
          exit 1
        fi

    - name: Configure GCP Auth
      if: contains(inputs.image_ref, 'docker.pkg.dev')
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ env.SA_JSON }}

    - name: Login to GCP Artifact Registry
      if: contains(inputs.image_ref, 'docker.pkg.dev')
      shell: bash
      env:
        IMAGE_REF: ${{ inputs.image_ref }}
      run: |
        REGISTRY_DOMAIN=$(echo "$IMAGE_REF" | cut -d'/' -f1)
        gcloud auth configure-docker "$REGISTRY_DOMAIN" --quiet

    # GHCR LOGIN
    - name: Log in to GitHub Container Registry
      if: contains(inputs.image_ref, 'ghcr.io')
      uses: docker/login-action@v4
      with:
        registry: ${{ inputs.ghcr_domain }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    # DockerHub Login
    - name: Log in to Docker Hub
      if: contains(inputs.image_ref, 'docker.io')
      uses: docker/login-action@v4
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}