# sentinel-1.conf
bind 0.0.0.0

# Port settings
port 26379
tls-port 26380

# TLS certificates and key for encrypted communication
tls-cert-file "/certs/redis.crt"
tls-key-file "/certs/redis.key"
tls-ca-cert-file "/certs/ca.crt"
# You can set this to 'yes' if you require client authentication
tls-auth-clients no
tls-replication yes

sentinel announce-hostnames yes
sentinel resolve-hostnames yes
sentinel monitor mymaster 192.168.0.192 6380 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000

# Auth sentinel to Redis master/replica
# sentinel auth-user <master-name> <username> not work in redis 7, sentinel always use default user
# sentinel auth-user mymaster admin
sentinel auth-pass mymaster supersecureadmin

# Auth sentinel to sentinel
sentinel sentinel-user admin
sentinel sentinel-pass onlysentinelpass

# users.acl
# user default on sanitize-payload #cfd635712e4e6928020615608c1ba69bac39fa635dc4d2b77e948af14ea48c91 ~* resetchannels -@all +ping +subscribe +info +sentinel +auth
# user default on sanitize-payload #cfd635712e4e6928020615608c1ba69bac39fa635dc4d2b77e948af14ea48c91 ~* &* +@all
user admin on sanitize-payload #cfd635712e4e6928020615608c1ba69bac39fa635dc4d2b77e948af14ea48c91 ~* resetchannels +@all
user default off sanitize-payload resetchannels -@all

# Logging debug, verbose, notice, warning
loglevel debug


