name: Action Test | env-prepare-auto
run-name: Action Test | env-prepare-auto - ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - feature/**
    tags:
      - v*


jobs:
  GlobalVariable:
    if: github.event.created == false
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.prepare.outputs.environment }}
      environment_suffix: ${{ steps.prepare.outputs.environment_suffix }}
      image_suffix: ${{ steps.prepare.outputs.image_suffix }}
      overlays_path: ${{ steps.prepare.outputs.overlays_path }}

      short_sha: ${{ steps.prepare.outputs.short_sha }}
      version: ${{ steps.prepare.outputs.version }}
      image_tag: ${{ steps.prepare.outputs.image_tag }}
      image_tag_latest: ${{ steps.prepare.outputs.image_tag_latest }}
      is_release: ${{ steps.prepare.outputs.is_release }}
      is_default_branch: ${{ steps.prepare.outputs.is_default_branch }}
      
    steps:
      - name: Prepare Environment
        id: prepare
        uses: ionehouten/devops-kangservice/.github/actions/env-prepare-auto@main
        with:
          development_pattern: "^(develop|feature/.*)$"
          staging_pattern: "^main$"
          provider: "GCP"
          image_name: "minipos"
          registry_domain: "asia-southeast2-docker.pkg.dev"
          registry_repo_dev: "hausapp-development-core"
          registry_repo_stg: "haus-staging-cluster"
          registry_repo_prd: "haus-production-main"



      - name: Debug
        run: |
          echo "environment: ${{ steps.prepare.outputs.environment }}"
          echo "environment_suffix: ${{ steps.prepare.outputs.environment_suffix }}"
          echo "image_suffix: ${{ steps.prepare.outputs.image_suffix }}"
          echo "overlays_path: ${{ steps.prepare.outputs.overlays_path }}"

          echo "short_sha: ${{ steps.prepare.outputs.short_sha }}"
          echo "version: ${{ steps.prepare.outputs.version }}"
          echo "image_tag: ${{ steps.prepare.outputs.image_tag }}"
          echo "image_tag_latest: ${{ steps.prepare.outputs.image_tag_latest }}"
          echo "is_release: ${{ steps.prepare.outputs.is_release }}"
          echo "is_default_branch: ${{ steps.prepare.outputs.is_default_branch }}"